/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_gestcomp (void)
{
  GtkWidget *window_gestcomp;
  GtkWidget *notebook2;
  GtkWidget *fixed18;
  GtkWidget *entry_id;
  GtkWidget *entry_prn;
  GtkWidget *entry_nom;
  GtkObject *spinbutton_jr_adj;
  GtkWidget *spinbutton_jr;
  GtkObject *spinbutton_an_adj;
  GtkWidget *spinbutton_an;
  GtkWidget *label1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *button_add;
  GtkWidget *alignment26;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label105;
  GtkWidget *checkbutton_confaj;
  GtkWidget *alignment25;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label104;
  GtkWidget *radiobutton_hom;
  GSList *radiobutton_hom_group = NULL;
  GtkWidget *radiobutton_fem;
  GtkWidget *comboboxentry_mois;
  GtkWidget *label133;
  GtkWidget *label134;
  GtkWidget *label135;
  GtkWidget *label101;
  GtkWidget *label100;
  GtkWidget *label98;
  GtkWidget *label97;
  GtkWidget *label99;
  GtkWidget *label141;
  GtkWidget *label2;
  GtkWidget *label62;
  GtkWidget *fixed19;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *alignment17;
  GtkWidget *button20;
  GtkWidget *alignment24;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label96;
  GtkWidget *label106;
  GtkWidget *label107;
  GtkWidget *label110;
  GtkWidget *entry_idmod;
  GtkWidget *entry_prnmod;
  GtkWidget *entry_nommod;
  GtkWidget *label109;
  GtkObject *spinbutton_jrmod_adj;
  GtkWidget *spinbutton_jrmod;
  GtkObject *spinbutton_anmod_adj;
  GtkWidget *spinbutton_anmod;
  GtkWidget *label108;
  GtkWidget *label_mod;
  GtkWidget *radiobutton_hommod;
  GSList *radiobutton_hommod_group = NULL;
  GtkWidget *radiobutton_femmod;
  GtkWidget *comboboxentry_moismod;
  GtkWidget *button_mod;
  GtkWidget *alignment28;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label112;
  GtkWidget *checkbutton_confmod;
  GtkWidget *alignment27;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label111;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *label137;
  GtkWidget *label138;
  GtkWidget *label136;
  GtkWidget *searchid;
  GtkWidget *label63;
  GtkWidget *fixed20;
  GtkWidget *label114;
  GtkWidget *entry_supp;
  GtkWidget *label_suppnn;
  GtkWidget *button_supp;
  GtkWidget *alignment29;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label117;
  GtkWidget *label_supsuc;
  GtkWidget *label64;
  GtkWidget *fixed21;
  GtkWidget *treeview3;
  GtkWidget *button_aff;
  GtkWidget *alignment30;
  GtkWidget *hbox29;
  GtkWidget *image29;
  GtkWidget *label118;
  GtkWidget *label65;
  GtkWidget *fixed22;
  GtkWidget *treeview4;
  GtkWidget *entry_rech;
  GtkWidget *button_rech;
  GtkWidget *alignment31;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label119;
  GtkWidget *label_rech;
  GtkWidget *label66;
  GtkWidget *fixed23;
  GtkWidget *entry7;
  GtkWidget *comboboxentry1;
  GtkWidget *calucler_facture;
  GtkWidget *label139;
  GtkWidget *label140;
  GtkWidget *label132;
  GtkWidget *label131;
  GtkWidget *label127;

  window_gestcomp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_gestcomp, 400, 200);
  gtk_window_set_title (GTK_WINDOW (window_gestcomp), _("G\303\251rer son compte"));

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (window_gestcomp), notebook2);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed18);
  gtk_widget_set_size_request (fixed18, 400, 300);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed18), entry_id, 248, 200);
  gtk_widget_set_size_request (entry_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  entry_prn = gtk_entry_new ();
  gtk_widget_show (entry_prn);
  gtk_fixed_put (GTK_FIXED (fixed18), entry_prn, 248, 240);
  gtk_widget_set_size_request (entry_prn, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prn), 8226);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed18), entry_nom, 248, 280);
  gtk_widget_set_size_request (entry_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  spinbutton_jr_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jr = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jr_adj), 1, 0);
  gtk_widget_show (spinbutton_jr);
  gtk_fixed_put (GTK_FIXED (fixed18), spinbutton_jr, 248, 320);
  gtk_widget_set_size_request (spinbutton_jr, 60, 27);

  spinbutton_an_adj = gtk_adjustment_new (1, 1999, 2025, 1, 10, 10);
  spinbutton_an = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_an_adj), 1, 0);
  gtk_widget_show (spinbutton_an);
  gtk_fixed_put (GTK_FIXED (fixed18), spinbutton_an, 520, 320);
  gtk_widget_set_size_request (spinbutton_an, 60, 27);

  label1 = gtk_label_new ("");
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed18), label1, 280, 56);
  gtk_widget_set_size_request (label1, 160, 17);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed18), entry1, 248, 360);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed18), entry2, 248, 400);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed18), entry3, 248, 440);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  button_add = gtk_button_new ();
  gtk_widget_show (button_add);
  gtk_fixed_put (GTK_FIXED (fixed18), button_add, 424, 520);
  gtk_widget_set_size_request (button_add, 104, 48);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button_add), alignment26);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label105 = gtk_label_new_with_mnemonic (_("<span foreground=\"darkred\" ><b>Ajouter</b></span>"));
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (hbox25), label105, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label105), TRUE);

  checkbutton_confaj = gtk_check_button_new ();
  gtk_widget_show (checkbutton_confaj);
  gtk_fixed_put (GTK_FIXED (fixed18), checkbutton_confaj, 160, 536);
  gtk_widget_set_size_request (checkbutton_confaj, 118, 24);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (checkbutton_confaj), alignment25);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("<span foreground=\"darkred\" ><b>Confirmer</b></span>"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox24), label104, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label104), TRUE);

  radiobutton_hom = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton_hom);
  gtk_fixed_put (GTK_FIXED (fixed18), radiobutton_hom, 200, 488);
  gtk_widget_set_size_request (radiobutton_hom, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_hom), radiobutton_hom_group);
  radiobutton_hom_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_hom));

  radiobutton_fem = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton_fem);
  gtk_fixed_put (GTK_FIXED (fixed18), radiobutton_fem, 344, 488);
  gtk_widget_set_size_request (radiobutton_fem, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_fem), radiobutton_hom_group);
  radiobutton_hom_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_fem));

  comboboxentry_mois = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_mois);
  gtk_fixed_put (GTK_FIXED (fixed18), comboboxentry_mois, 320, 320);
  gtk_widget_set_size_request (comboboxentry_mois, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("Janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("fevrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("may"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("aout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mois), _("decembre"));

  label133 = gtk_label_new (_("<span foreground=\"black\" ><b>adresse</b></span>"));
  gtk_widget_show (label133);
  gtk_fixed_put (GTK_FIXED (fixed18), label133, 80, 360);
  gtk_widget_set_size_request (label133, 81, 17);
  gtk_label_set_use_markup (GTK_LABEL (label133), TRUE);

  label134 = gtk_label_new (_("<span foreground=\"black\" ><b>mot de passe</b></span>"));
  gtk_widget_show (label134);
  gtk_fixed_put (GTK_FIXED (fixed18), label134, 80, 400);
  gtk_widget_set_size_request (label134, 113, 25);
  gtk_label_set_use_markup (GTK_LABEL (label134), TRUE);

  label135 = gtk_label_new (_("<span foreground=\"black\" ><b>Email</b></span>"));
  gtk_widget_show (label135);
  gtk_fixed_put (GTK_FIXED (fixed18), label135, 80, 448);
  gtk_widget_set_size_request (label135, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label135), TRUE);

  label101 = gtk_label_new (_("<span foreground=\"black\" ><b>Sexe</b></span>"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed18), label101, 80, 488);
  gtk_widget_set_size_request (label101, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label101), TRUE);

  label100 = gtk_label_new (_("<span foreground=\"black\" ><b>Date de Naissance</b></span>"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed18), label100, 88, 320);
  gtk_widget_set_size_request (label100, 136, 24);
  gtk_label_set_use_markup (GTK_LABEL (label100), TRUE);

  label98 = gtk_label_new (_("<span foreground=\"black\" ><b>Prenom</b></span>"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed18), label98, 72, 240);
  gtk_widget_set_size_request (label98, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (label98), TRUE);

  label97 = gtk_label_new (_("<span foreground=\"black\" ><b>Id citoyen</b></span>"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed18), label97, 80, 200);
  gtk_widget_set_size_request (label97, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (label97), TRUE);

  label99 = gtk_label_new (_("<span foreground=\"black\" ><b>Nom</b></span>"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed18), label99, 72, 280);
  gtk_widget_set_size_request (label99, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label99), TRUE);

  label141 = gtk_label_new (_("<u><span  font_size=\"20000\" > <span foreground=\"navy\">Optimiser votre stationnement avec notre application !\n\n R\303\251servez,g\303\251rez et trouvez des places en toute simplicit\303\251 \n\n\n--</span></span></u>"));
  gtk_widget_show (label141);
  gtk_fixed_put (GTK_FIXED (fixed18), label141, 120, 24);
  gtk_widget_set_size_request (label141, 744, 128);
  gtk_label_set_use_markup (GTK_LABEL (label141), TRUE);

  label2 = gtk_label_new ("");
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed18), label2, 600, 208);
  gtk_widget_set_size_request (label2, 280, 72);

  label62 = gtk_label_new (_("<span foreground=\"navy\" ><b>Ajouter</b></span>"));
  gtk_widget_show (label62);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label62);
  gtk_label_set_use_markup (GTK_LABEL (label62), TRUE);

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed19);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_fixed_put (GTK_FIXED (fixed19), alignment15, 0, 0);
  gtk_widget_set_size_request (alignment15, 0, 0);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 0);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_fixed_put (GTK_FIXED (fixed19), alignment16, 0, 0);
  gtk_widget_set_size_request (alignment16, 0, 0);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_box_pack_start (GTK_BOX (hbox16), alignment17, FALSE, FALSE, 0);

  button20 = gtk_button_new ();
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed19), button20, 680, 320);
  gtk_widget_set_size_request (button20, 280, 69);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button20), alignment24);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("<span foreground=\"darkred\" ><b>confirmer</b></span>"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox23), label96, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label96), TRUE);

  label106 = gtk_label_new (_("<span foreground=\"black\" ><b>Id citoyen</b></span>"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed19), label106, 32, 48);
  gtk_widget_set_size_request (label106, 112, 40);
  gtk_label_set_use_markup (GTK_LABEL (label106), TRUE);

  label107 = gtk_label_new (_("<span foreground=\"black\" ><b>Prenom</b></span>"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed19), label107, 16, 88);
  gtk_widget_set_size_request (label107, 144, 40);
  gtk_label_set_use_markup (GTK_LABEL (label107), TRUE);

  label110 = gtk_label_new (_("<span foreground=\"black\" ><b>Sexe</b></span>"));
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed19), label110, 0, 224);
  gtk_widget_set_size_request (label110, 168, 40);
  gtk_label_set_use_markup (GTK_LABEL (label110), TRUE);

  entry_idmod = gtk_entry_new ();
  gtk_widget_show (entry_idmod);
  gtk_fixed_put (GTK_FIXED (fixed19), entry_idmod, 160, 56);
  gtk_widget_set_size_request (entry_idmod, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idmod), 8226);

  entry_prnmod = gtk_entry_new ();
  gtk_widget_show (entry_prnmod);
  gtk_fixed_put (GTK_FIXED (fixed19), entry_prnmod, 160, 96);
  gtk_widget_set_size_request (entry_prnmod, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prnmod), 8226);

  entry_nommod = gtk_entry_new ();
  gtk_widget_show (entry_nommod);
  gtk_fixed_put (GTK_FIXED (fixed19), entry_nommod, 160, 144);
  gtk_widget_set_size_request (entry_nommod, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nommod), 8226);

  label109 = gtk_label_new (_("<span foreground=\"black\" ><b>Date de Naissance</b></span>"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed19), label109, 0, 184);
  gtk_widget_set_size_request (label109, 176, 33);
  gtk_label_set_use_markup (GTK_LABEL (label109), TRUE);

  spinbutton_jrmod_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton_jrmod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jrmod_adj), 1, 0);
  gtk_widget_show (spinbutton_jrmod);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbutton_jrmod, 184, 192);
  gtk_widget_set_size_request (spinbutton_jrmod, 60, 27);

  spinbutton_anmod_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton_anmod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_anmod_adj), 1, 0);
  gtk_widget_show (spinbutton_anmod);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbutton_anmod, 440, 192);
  gtk_widget_set_size_request (spinbutton_anmod, 60, 27);

  label108 = gtk_label_new (_("<span foreground=\"black\" ><b>Nom</b></span>"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed19), label108, 0, 128);
  gtk_widget_set_size_request (label108, 168, 40);
  gtk_label_set_use_markup (GTK_LABEL (label108), TRUE);

  label_mod = gtk_label_new ("");
  gtk_widget_show (label_mod);
  gtk_fixed_put (GTK_FIXED (fixed19), label_mod, 456, 288);
  gtk_widget_set_size_request (label_mod, 112, 48);

  radiobutton_hommod = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton_hommod);
  gtk_fixed_put (GTK_FIXED (fixed19), radiobutton_hommod, 168, 232);
  gtk_widget_set_size_request (radiobutton_hommod, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_hommod), radiobutton_hommod_group);
  radiobutton_hommod_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_hommod));

  radiobutton_femmod = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton_femmod);
  gtk_fixed_put (GTK_FIXED (fixed19), radiobutton_femmod, 296, 232);
  gtk_widget_set_size_request (radiobutton_femmod, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_femmod), radiobutton_hommod_group);
  radiobutton_hommod_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_femmod));

  comboboxentry_moismod = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_moismod);
  gtk_fixed_put (GTK_FIXED (fixed19), comboboxentry_moismod, 248, 192);
  gtk_widget_set_size_request (comboboxentry_moismod, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("Janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("fevrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("may"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("aout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_moismod), _("decembre"));

  button_mod = gtk_button_new ();
  gtk_widget_show (button_mod);
  gtk_fixed_put (GTK_FIXED (fixed19), button_mod, 312, 448);
  gtk_widget_set_size_request (button_mod, 112, 48);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button_mod), alignment28);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label112 = gtk_label_new_with_mnemonic (_("<span foreground=\"darkred\" ><b>Modifier</b></span>"));
  gtk_widget_show (label112);
  gtk_box_pack_start (GTK_BOX (hbox27), label112, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label112), TRUE);

  checkbutton_confmod = gtk_check_button_new ();
  gtk_widget_show (checkbutton_confmod);
  gtk_fixed_put (GTK_FIXED (fixed19), checkbutton_confmod, 80, 456);
  gtk_widget_set_size_request (checkbutton_confmod, 118, 24);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (checkbutton_confmod), alignment27);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label111 = gtk_label_new_with_mnemonic (_("<span foreground=\"darkred\" ><b>Confirmer modification</b></span>"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox26), label111, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label111), TRUE);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed19), entry4, 160, 272);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed19), entry5, 160, 304);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed19), entry6, 160, 336);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  label137 = gtk_label_new (_("<span foreground=\"black\" ><b>Adresse</b></span>"));
  gtk_widget_show (label137);
  gtk_fixed_put (GTK_FIXED (fixed19), label137, 48, 280);
  gtk_widget_set_size_request (label137, 80, 17);
  gtk_label_set_use_markup (GTK_LABEL (label137), TRUE);

  label138 = gtk_label_new (_("<span foreground=\"black\" ><b>mot de passe </b></span>"));
  gtk_widget_show (label138);
  gtk_fixed_put (GTK_FIXED (fixed19), label138, 32, 312);
  gtk_widget_set_size_request (label138, 105, 16);
  gtk_label_set_use_markup (GTK_LABEL (label138), TRUE);

  label136 = gtk_label_new (_("<span foreground=\"black\" ><b>Email</b></span>"));
  gtk_widget_show (label136);
  gtk_fixed_put (GTK_FIXED (fixed19), label136, 24, 344);
  gtk_widget_set_size_request (label136, 81, 17);
  gtk_label_set_use_markup (GTK_LABEL (label136), TRUE);

  searchid = gtk_button_new_with_mnemonic (_("search"));
  gtk_widget_show (searchid);
  gtk_fixed_put (GTK_FIXED (fixed19), searchid, 328, 56);
  gtk_widget_set_size_request (searchid, 74, 29);

  label63 = gtk_label_new (_("<span foreground=\"navy\" ><b>modifier</b></span>"));
  gtk_widget_show (label63);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label63);
  gtk_label_set_use_markup (GTK_LABEL (label63), TRUE);

  fixed20 = gtk_fixed_new ();
  gtk_widget_show (fixed20);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed20);

  label114 = gtk_label_new (_("<span foreground=\"black\" ><b>Id citoyen</b></span>"));
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed20), label114, 16, 64);
  gtk_widget_set_size_request (label114, 112, 48);
  gtk_label_set_use_markup (GTK_LABEL (label114), TRUE);

  entry_supp = gtk_entry_new ();
  gtk_widget_show (entry_supp);
  gtk_fixed_put (GTK_FIXED (fixed20), entry_supp, 168, 72);
  gtk_widget_set_size_request (entry_supp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_supp), 8226);

  label_suppnn = gtk_label_new ("");
  gtk_widget_show (label_suppnn);
  gtk_fixed_put (GTK_FIXED (fixed20), label_suppnn, 416, 120);
  gtk_widget_set_size_request (label_suppnn, 136, 72);

  button_supp = gtk_button_new ();
  gtk_widget_show (button_supp);
  gtk_fixed_put (GTK_FIXED (fixed20), button_supp, 184, 136);
  gtk_widget_set_size_request (button_supp, 120, 48);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button_supp), alignment29);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label117 = gtk_label_new_with_mnemonic (_("<span foreground=\"darkred\" ><b>Supprimer</b></span>"));
  gtk_widget_show (label117);
  gtk_box_pack_start (GTK_BOX (hbox28), label117, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label117), TRUE);

  label_supsuc = gtk_label_new ("");
  gtk_widget_show (label_supsuc);
  gtk_fixed_put (GTK_FIXED (fixed20), label_supsuc, 496, 96);
  gtk_widget_set_size_request (label_supsuc, 320, 72);

  label64 = gtk_label_new (_("<span foreground=\"navy\" ><b>supprimer</b></span>"));
  gtk_widget_show (label64);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label64);
  gtk_label_set_use_markup (GTK_LABEL (label64), TRUE);

  fixed21 = gtk_fixed_new ();
  gtk_widget_show (fixed21);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed21);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed21), treeview3, 48, 32);
  gtk_widget_set_size_request (treeview3, 560, 328);

  button_aff = gtk_button_new ();
  gtk_widget_show (button_aff);
  gtk_fixed_put (GTK_FIXED (fixed21), button_aff, 280, 400);
  gtk_widget_set_size_request (button_aff, 120, 56);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (button_aff), alignment30);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox29);

  image29 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox29), image29, FALSE, FALSE, 0);

  label118 = gtk_label_new_with_mnemonic (_("<span foreground=\"darkred\" ><b>Afficher</b></span>"));
  gtk_widget_show (label118);
  gtk_box_pack_start (GTK_BOX (hbox29), label118, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label118), TRUE);

  label65 = gtk_label_new (_("<span foreground=\"navy\" ><b>Afficher</b></span>"));
  gtk_widget_show (label65);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label65);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed22);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed22), treeview4, 72, 32);
  gtk_widget_set_size_request (treeview4, 488, 216);

  entry_rech = gtk_entry_new ();
  gtk_widget_show (entry_rech);
  gtk_fixed_put (GTK_FIXED (fixed22), entry_rech, 264, 296);
  gtk_widget_set_size_request (entry_rech, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_rech), 8226);

  button_rech = gtk_button_new ();
  gtk_widget_show (button_rech);
  gtk_fixed_put (GTK_FIXED (fixed22), button_rech, 144, 288);
  gtk_widget_set_size_request (button_rech, 112, 48);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (button_rech), alignment31);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label119 = gtk_label_new_with_mnemonic (_("<span foreground=\"navy\" ><b>rechercher</b></span>"));
  gtk_widget_show (label119);
  gtk_box_pack_start (GTK_BOX (hbox30), label119, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label119), TRUE);

  label_rech = gtk_label_new ("");
  gtk_widget_show (label_rech);
  gtk_fixed_put (GTK_FIXED (fixed22), label_rech, 544, 280);
  gtk_widget_set_size_request (label_rech, 328, 64);

  label66 = gtk_label_new (_("<span foreground=\"navy\" ><b>Recherche</b></span>"));
  gtk_widget_show (label66);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 4), label66);
  gtk_label_set_use_markup (GTK_LABEL (label66), TRUE);

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed23);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed23), entry7, 216, 128);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed23), comboboxentry1, 216, 168);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("january "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("february "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("march "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("april "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("june "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("july "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("august "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("september "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("october "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("november"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("december"));

  calucler_facture = gtk_button_new_with_mnemonic (_("calculer facture"));
  gtk_widget_show (calucler_facture);
  gtk_fixed_put (GTK_FIXED (fixed23), calucler_facture, 408, 160);
  gtk_widget_set_size_request (calucler_facture, 184, 37);

  label139 = gtk_label_new (_("<span foreground=\"black\" ><b>id</b></span>"));
  gtk_widget_show (label139);
  gtk_fixed_put (GTK_FIXED (fixed23), label139, 144, 136);
  gtk_widget_set_size_request (label139, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label139), TRUE);

  label140 = gtk_label_new (_("<span foreground=\"black\" ><b>mois</b></span>"));
  gtk_widget_show (label140);
  gtk_fixed_put (GTK_FIXED (fixed23), label140, 144, 176);
  gtk_widget_set_size_request (label140, 57, 17);
  gtk_label_set_use_markup (GTK_LABEL (label140), TRUE);

  label132 = gtk_label_new ("");
  gtk_widget_show (label132);
  gtk_fixed_put (GTK_FIXED (fixed23), label132, 192, 208);
  gtk_widget_set_size_request (label132, 384, 128);

  label131 = gtk_label_new (_("<span foreground=\"navy\" ><b>votre facture est</b></span>"));
  gtk_widget_show (label131);
  gtk_fixed_put (GTK_FIXED (fixed23), label131, 32, 232);
  gtk_widget_set_size_request (label131, 169, 33);
  gtk_label_set_use_markup (GTK_LABEL (label131), TRUE);

  label127 = gtk_label_new (_("<span foreground=\"navy\" ><b>facture</b></span>"));
  gtk_widget_show (label127);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 5), label127);
  gtk_label_set_use_markup (GTK_LABEL (label127), TRUE);

  g_signal_connect ((gpointer) button_add, "clicked",
                    G_CALLBACK (on_button_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_confaj, "toggled",
                    G_CALLBACK (on_checkbutton_confaj_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_hom, "toggled",
                    G_CALLBACK (on_radiobutton_hom_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_fem, "toggled",
                    G_CALLBACK (on_radiobutton_fem_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_hommod, "toggled",
                    G_CALLBACK (on_radiobutton_hommod_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_femmod, "toggled",
                    G_CALLBACK (on_radiobutton_femmod_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_mod, "clicked",
                    G_CALLBACK (on_button_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_confmod, "toggled",
                    G_CALLBACK (on_checkbutton_confmod_toggled),
                    NULL);
 /* g_signal_connect ((gpointer) searchid, "clicked",
                    G_CALLBACK (on_searchid_clicked),
                    NULL);*/
  g_signal_connect ((gpointer) button_supp, "clicked",
                    G_CALLBACK (on_button_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview3, "row_activated",
                    G_CALLBACK (on_treeview3_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_aff, "clicked",
                    G_CALLBACK (on_button_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview4, "row_activated",
                    G_CALLBACK (on_treeview4_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_rech, "clicked",
                    G_CALLBACK (on_button_rech_clicked),
                    NULL);
  g_signal_connect ((gpointer) calucler_facture, "clicked",
                    G_CALLBACK (on_calucler_facture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_gestcomp, window_gestcomp, "window_gestcomp");
  GLADE_HOOKUP_OBJECT (window_gestcomp, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (window_gestcomp, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry_prn, "entry_prn");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (window_gestcomp, spinbutton_jr, "spinbutton_jr");
  GLADE_HOOKUP_OBJECT (window_gestcomp, spinbutton_an, "spinbutton_an");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label1, "label1");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window_gestcomp, button_add, "button_add");
  GLADE_HOOKUP_OBJECT (window_gestcomp, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window_gestcomp, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window_gestcomp, image25, "image25");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label105, "label105");
  GLADE_HOOKUP_OBJECT (window_gestcomp, checkbutton_confaj, "checkbutton_confaj");
  GLADE_HOOKUP_OBJECT (window_gestcomp, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window_gestcomp, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window_gestcomp, image24, "image24");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label104, "label104");
  GLADE_HOOKUP_OBJECT (window_gestcomp, radiobutton_hom, "radiobutton_hom");
  GLADE_HOOKUP_OBJECT (window_gestcomp, radiobutton_fem, "radiobutton_fem");
  GLADE_HOOKUP_OBJECT (window_gestcomp, comboboxentry_mois, "comboboxentry_mois");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label133, "label133");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label134, "label134");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label135, "label135");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label101, "label101");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label100, "label100");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label98, "label98");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label97, "label97");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label99, "label99");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label141, "label141");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label2, "label2");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label62, "label62");
  GLADE_HOOKUP_OBJECT (window_gestcomp, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (window_gestcomp, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window_gestcomp, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window_gestcomp, image16, "image16");
  GLADE_HOOKUP_OBJECT (window_gestcomp, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window_gestcomp, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window_gestcomp, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window_gestcomp, button20, "button20");
  GLADE_HOOKUP_OBJECT (window_gestcomp, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window_gestcomp, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window_gestcomp, image23, "image23");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label96, "label96");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label106, "label106");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label107, "label107");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label110, "label110");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry_idmod, "entry_idmod");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry_prnmod, "entry_prnmod");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry_nommod, "entry_nommod");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label109, "label109");
  GLADE_HOOKUP_OBJECT (window_gestcomp, spinbutton_jrmod, "spinbutton_jrmod");
  GLADE_HOOKUP_OBJECT (window_gestcomp, spinbutton_anmod, "spinbutton_anmod");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label108, "label108");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label_mod, "label_mod");
  GLADE_HOOKUP_OBJECT (window_gestcomp, radiobutton_hommod, "radiobutton_hommod");
  GLADE_HOOKUP_OBJECT (window_gestcomp, radiobutton_femmod, "radiobutton_femmod");
  GLADE_HOOKUP_OBJECT (window_gestcomp, comboboxentry_moismod, "comboboxentry_moismod");
  GLADE_HOOKUP_OBJECT (window_gestcomp, button_mod, "button_mod");
  GLADE_HOOKUP_OBJECT (window_gestcomp, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window_gestcomp, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window_gestcomp, image27, "image27");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label112, "label112");
  GLADE_HOOKUP_OBJECT (window_gestcomp, checkbutton_confmod, "checkbutton_confmod");
  GLADE_HOOKUP_OBJECT (window_gestcomp, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window_gestcomp, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window_gestcomp, image26, "image26");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label111, "label111");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label137, "label137");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label138, "label138");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label136, "label136");
  GLADE_HOOKUP_OBJECT (window_gestcomp, searchid, "searchid");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label63, "label63");
  GLADE_HOOKUP_OBJECT (window_gestcomp, fixed20, "fixed20");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label114, "label114");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry_supp, "entry_supp");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label_suppnn, "label_suppnn");
  GLADE_HOOKUP_OBJECT (window_gestcomp, button_supp, "button_supp");
  GLADE_HOOKUP_OBJECT (window_gestcomp, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window_gestcomp, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (window_gestcomp, image28, "image28");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label117, "label117");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label_supsuc, "label_supsuc");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label64, "label64");
  GLADE_HOOKUP_OBJECT (window_gestcomp, fixed21, "fixed21");
  GLADE_HOOKUP_OBJECT (window_gestcomp, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window_gestcomp, button_aff, "button_aff");
  GLADE_HOOKUP_OBJECT (window_gestcomp, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window_gestcomp, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (window_gestcomp, image29, "image29");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label118, "label118");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label65, "label65");
  GLADE_HOOKUP_OBJECT (window_gestcomp, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (window_gestcomp, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry_rech, "entry_rech");
  GLADE_HOOKUP_OBJECT (window_gestcomp, button_rech, "button_rech");
  GLADE_HOOKUP_OBJECT (window_gestcomp, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (window_gestcomp, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (window_gestcomp, image30, "image30");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label119, "label119");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label_rech, "label_rech");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label66, "label66");
  GLADE_HOOKUP_OBJECT (window_gestcomp, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (window_gestcomp, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window_gestcomp, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window_gestcomp, calucler_facture, "calucler_facture");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label139, "label139");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label140, "label140");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label132, "label132");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label131, "label131");
  GLADE_HOOKUP_OBJECT (window_gestcomp, label127, "label127");

  return window_gestcomp;
}

