/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajouter (void);
GtkWidget* create_modifier (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_afficher (void);
GtkWidget* create_tachesupplementaire (void);
GtkWidget* create_menu (void);
GtkWidget* create_chercher (void);
GtkWidget* create_goodbye (void);
