/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajouter (void)
{
  GtkWidget *ajouter;
  GtkWidget *fixed1;
  GtkWidget *entryNom;
  GtkWidget *entryPrenom;
  GtkObject *spin1_adj;
  GtkWidget *spin1;
  GtkObject *spin2_adj;
  GtkWidget *spin2;
  GtkObject *spin3_adj;
  GtkWidget *spin3;
  GtkWidget *entryEtatsanitaire;
  GtkWidget *entryNumerodetelephone;
  GtkWidget *entryLogin;
  GtkWidget *entryMotdepasse;
  GtkWidget *entryAdressemail;
  GtkWidget *entryEtatcivil;
  GtkWidget *entrycin;
  GtkWidget *labelNum__ro_de_t__l__phone;
  GtkWidget *labelAdresse_mail;
  GtkWidget *etatpcomboboxentry1;
  GtkWidget *labelPoste_d__sirant;
  GtkWidget *labelLogin;
  GtkWidget *labelMot_de_passe;
  GtkWidget *labelajouter_un_agent;
  GtkWidget *precedentajouter;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label59;
  GtkWidget *suivantajouter;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label60;
  GtkWidget *buttannuler;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label15;
  GtkWidget *buttonajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label14;
  GtkWidget *labelSexe;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *labelEtat_civil;
  GtkWidget *radiobutton2;
  GtkWidget *labelEtat_sanitaire;
  GtkWidget *labelDate_de_naissance;
  GtkWidget *labelcin;
  GtkWidget *labelPr__nom;
  GtkWidget *labelNom;

  ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter), _("ajouter"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajouter), fixed1);
  gtk_container_set_border_width (GTK_CONTAINER (fixed1), 4);

  entryNom = gtk_entry_new ();
  gtk_widget_show (entryNom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNom, 152, 128);
  gtk_widget_set_size_request (entryNom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom), 8226);

  entryPrenom = gtk_entry_new ();
  gtk_widget_show (entryPrenom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryPrenom, 152, 184);
  gtk_widget_set_size_request (entryPrenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrenom), 8226);

  spin1_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spin1 = gtk_spin_button_new (GTK_ADJUSTMENT (spin1_adj), 1, 0);
  gtk_widget_show (spin1);
  gtk_fixed_put (GTK_FIXED (fixed1), spin1, 176, 320);
  gtk_widget_set_size_request (spin1, 60, 27);

  spin2_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  spin2 = gtk_spin_button_new (GTK_ADJUSTMENT (spin2_adj), 1, 0);
  gtk_widget_show (spin2);
  gtk_fixed_put (GTK_FIXED (fixed1), spin2, 256, 320);
  gtk_widget_set_size_request (spin2, 60, 27);

  spin3_adj = gtk_adjustment_new (1, 0, 2024, 1, 10, 10);
  spin3 = gtk_spin_button_new (GTK_ADJUSTMENT (spin3_adj), 1, 0);
  gtk_widget_show (spin3);
  gtk_fixed_put (GTK_FIXED (fixed1), spin3, 336, 320);
  gtk_widget_set_size_request (spin3, 60, 27);

  entryEtatsanitaire = gtk_entry_new ();
  gtk_widget_show (entryEtatsanitaire);
  gtk_fixed_put (GTK_FIXED (fixed1), entryEtatsanitaire, 856, 112);
  gtk_widget_set_size_request (entryEtatsanitaire, 196, 31);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryEtatsanitaire), 8226);

  entryNumerodetelephone = gtk_entry_new ();
  gtk_widget_show (entryNumerodetelephone);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNumerodetelephone, 856, 168);
  gtk_widget_set_size_request (entryNumerodetelephone, 188, 31);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNumerodetelephone), 8226);

  entryLogin = gtk_entry_new ();
  gtk_widget_show (entryLogin);
  gtk_fixed_put (GTK_FIXED (fixed1), entryLogin, 872, 384);
  gtk_widget_set_size_request (entryLogin, 196, 31);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLogin), 8226);

  entryMotdepasse = gtk_entry_new ();
  gtk_widget_show (entryMotdepasse);
  gtk_fixed_put (GTK_FIXED (fixed1), entryMotdepasse, 872, 456);
  gtk_widget_set_size_request (entryMotdepasse, 188, 31);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMotdepasse), 8226);

  entryAdressemail = gtk_entry_new ();
  gtk_widget_show (entryAdressemail);
  gtk_fixed_put (GTK_FIXED (fixed1), entryAdressemail, 864, 232);
  gtk_widget_set_size_request (entryAdressemail, 184, 31);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAdressemail), 8226);

  entryEtatcivil = gtk_entry_new ();
  gtk_widget_show (entryEtatcivil);
  gtk_fixed_put (GTK_FIXED (fixed1), entryEtatcivil, 168, 472);
  gtk_widget_set_size_request (entryEtatcivil, 199, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryEtatcivil), 8226);

  entrycin = gtk_entry_new ();
  gtk_widget_show (entrycin);
  gtk_fixed_put (GTK_FIXED (fixed1), entrycin, 160, 248);
  gtk_widget_set_size_request (entrycin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycin), 8226);

  labelNum__ro_de_t__l__phone = gtk_label_new (_("Num\303\251ro de t\303\251l\303\251phone :"));
  gtk_widget_show (labelNum__ro_de_t__l__phone);
  gtk_fixed_put (GTK_FIXED (fixed1), labelNum__ro_de_t__l__phone, 616, 168);
  gtk_widget_set_size_request (labelNum__ro_de_t__l__phone, 208, 32);

  labelAdresse_mail = gtk_label_new (_("Adresse mail :"));
  gtk_widget_show (labelAdresse_mail);
  gtk_fixed_put (GTK_FIXED (fixed1), labelAdresse_mail, 584, 240);
  gtk_widget_set_size_request (labelAdresse_mail, 272, 24);

  etatpcomboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (etatpcomboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed1), etatpcomboboxentry1, 872, 304);
  gtk_widget_set_size_request (etatpcomboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (etatpcomboboxentry1), _("azerty"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (etatpcomboboxentry1), _("sdfghj"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (etatpcomboboxentry1), _("sdfg"));

  labelPoste_d__sirant = gtk_label_new (_("Poste d\303\251sirant :"));
  gtk_widget_show (labelPoste_d__sirant);
  gtk_fixed_put (GTK_FIXED (fixed1), labelPoste_d__sirant, 640, 312);
  gtk_widget_set_size_request (labelPoste_d__sirant, 184, 25);

  labelLogin = gtk_label_new (_("Login :"));
  gtk_widget_show (labelLogin);
  gtk_fixed_put (GTK_FIXED (fixed1), labelLogin, 624, 376);
  gtk_widget_set_size_request (labelLogin, 172, 52);

  labelMot_de_passe = gtk_label_new (_("Mot de passe :"));
  gtk_widget_show (labelMot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed1), labelMot_de_passe, 624, 456);
  gtk_widget_set_size_request (labelMot_de_passe, 204, 44);

  labelajouter_un_agent = gtk_label_new (_("AJOUTER UN AGENT :"));
  gtk_widget_show (labelajouter_un_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), labelajouter_un_agent, 440, 16);
  gtk_widget_set_size_request (labelajouter_un_agent, 240, 39);

  precedentajouter = gtk_button_new ();
  gtk_widget_show (precedentajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), precedentajouter, 8, 824);
  gtk_widget_set_size_request (precedentajouter, 148, 57);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (precedentajouter), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("pr\303\251c\303\251dent"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox19), label59, FALSE, FALSE, 0);

  suivantajouter = gtk_button_new ();
  gtk_widget_show (suivantajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), suivantajouter, 1072, 824);
  gtk_widget_set_size_request (suivantajouter, 140, 57);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (suivantajouter), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("suivant"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox20), label60, FALSE, FALSE, 0);

  buttannuler = gtk_button_new ();
  gtk_widget_show (buttannuler);
  gtk_fixed_put (GTK_FIXED (fixed1), buttannuler, 528, 688);
  gtk_widget_set_size_request (buttannuler, 180, 57);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttannuler), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox2), label15, FALSE, FALSE, 0);

  buttonajouter = gtk_button_new ();
  gtk_widget_show (buttonajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonajouter, 528, 608);
  gtk_widget_set_size_request (buttonajouter, 180, 57);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox1), label14, FALSE, FALSE, 0);

  labelSexe = gtk_label_new (_("Sexe :"));
  gtk_widget_show (labelSexe);
  gtk_fixed_put (GTK_FIXED (fixed1), labelSexe, 24, 376);
  gtk_widget_set_size_request (labelSexe, 84, 53);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("homme "));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1, 152, 368);
  gtk_widget_set_size_request (radiobutton1, 116, 68);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  labelEtat_civil = gtk_label_new (_("\303\211tat civil  "));
  gtk_widget_show (labelEtat_civil);
  gtk_fixed_put (GTK_FIXED (fixed1), labelEtat_civil, 0, 464);
  gtk_widget_set_size_request (labelEtat_civil, 204, 45);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton2, 288, 352);
  gtk_widget_set_size_request (radiobutton2, 136, 92);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  labelEtat_sanitaire = gtk_label_new (_("Etat sanitaire :"));
  gtk_widget_show (labelEtat_sanitaire);
  gtk_fixed_put (GTK_FIXED (fixed1), labelEtat_sanitaire, 592, 112);
  gtk_widget_set_size_request (labelEtat_sanitaire, 224, 24);

  labelDate_de_naissance = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (labelDate_de_naissance);
  gtk_fixed_put (GTK_FIXED (fixed1), labelDate_de_naissance, 8, 312);
  gtk_widget_set_size_request (labelDate_de_naissance, 156, 44);

  labelcin = gtk_label_new (_("Num\303\251ro CIN:"));
  gtk_widget_show (labelcin);
  gtk_fixed_put (GTK_FIXED (fixed1), labelcin, 16, 248);
  gtk_widget_set_size_request (labelcin, 124, 36);

  labelPr__nom = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (labelPr__nom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelPr__nom, 24, 176);
  gtk_widget_set_size_request (labelPr__nom, 92, 36);

  labelNom = gtk_label_new (_("Nom :"));
  gtk_widget_show (labelNom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelNom, 24, 120);
  gtk_widget_set_size_request (labelNom, 100, 45);

  g_signal_connect ((gpointer) precedentajouter, "clicked",
                    G_CALLBACK (on_precedentajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) suivantajouter, "clicked",
                    G_CALLBACK (on_suivantajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttannuler, "clicked",
                    G_CALLBACK (on_buttannuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonajouter, "clicked",
                    G_CALLBACK (on_buttonajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajouter, entryNom, "entryNom");
  GLADE_HOOKUP_OBJECT (ajouter, entryPrenom, "entryPrenom");
  GLADE_HOOKUP_OBJECT (ajouter, spin1, "spin1");
  GLADE_HOOKUP_OBJECT (ajouter, spin2, "spin2");
  GLADE_HOOKUP_OBJECT (ajouter, spin3, "spin3");
  GLADE_HOOKUP_OBJECT (ajouter, entryEtatsanitaire, "entryEtatsanitaire");
  GLADE_HOOKUP_OBJECT (ajouter, entryNumerodetelephone, "entryNumerodetelephone");
  GLADE_HOOKUP_OBJECT (ajouter, entryLogin, "entryLogin");
  GLADE_HOOKUP_OBJECT (ajouter, entryMotdepasse, "entryMotdepasse");
  GLADE_HOOKUP_OBJECT (ajouter, entryAdressemail, "entryAdressemail");
  GLADE_HOOKUP_OBJECT (ajouter, entryEtatcivil, "entryEtatcivil");
  GLADE_HOOKUP_OBJECT (ajouter, entrycin, "entrycin");
  GLADE_HOOKUP_OBJECT (ajouter, labelNum__ro_de_t__l__phone, "labelNum__ro_de_t__l__phone");
  GLADE_HOOKUP_OBJECT (ajouter, labelAdresse_mail, "labelAdresse_mail");
  GLADE_HOOKUP_OBJECT (ajouter, etatpcomboboxentry1, "etatpcomboboxentry1");
  GLADE_HOOKUP_OBJECT (ajouter, labelPoste_d__sirant, "labelPoste_d__sirant");
  GLADE_HOOKUP_OBJECT (ajouter, labelLogin, "labelLogin");
  GLADE_HOOKUP_OBJECT (ajouter, labelMot_de_passe, "labelMot_de_passe");
  GLADE_HOOKUP_OBJECT (ajouter, labelajouter_un_agent, "labelajouter_un_agent");
  GLADE_HOOKUP_OBJECT (ajouter, precedentajouter, "precedentajouter");
  GLADE_HOOKUP_OBJECT (ajouter, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (ajouter, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (ajouter, image19, "image19");
  GLADE_HOOKUP_OBJECT (ajouter, label59, "label59");
  GLADE_HOOKUP_OBJECT (ajouter, suivantajouter, "suivantajouter");
  GLADE_HOOKUP_OBJECT (ajouter, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (ajouter, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (ajouter, image20, "image20");
  GLADE_HOOKUP_OBJECT (ajouter, label60, "label60");
  GLADE_HOOKUP_OBJECT (ajouter, buttannuler, "buttannuler");
  GLADE_HOOKUP_OBJECT (ajouter, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ajouter, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ajouter, image2, "image2");
  GLADE_HOOKUP_OBJECT (ajouter, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajouter, buttonajouter, "buttonajouter");
  GLADE_HOOKUP_OBJECT (ajouter, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajouter, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajouter, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajouter, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajouter, labelSexe, "labelSexe");
  GLADE_HOOKUP_OBJECT (ajouter, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (ajouter, labelEtat_civil, "labelEtat_civil");
  GLADE_HOOKUP_OBJECT (ajouter, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (ajouter, labelEtat_sanitaire, "labelEtat_sanitaire");
  GLADE_HOOKUP_OBJECT (ajouter, labelDate_de_naissance, "labelDate_de_naissance");
  GLADE_HOOKUP_OBJECT (ajouter, labelcin, "labelcin");
  GLADE_HOOKUP_OBJECT (ajouter, labelPr__nom, "labelPr__nom");
  GLADE_HOOKUP_OBJECT (ajouter, labelNom, "labelNom");

  return ajouter;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed2;
  GtkWidget *entryn;
  GtkWidget *entryp;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *entryes;
  GtkWidget *entrynt;
  GtkWidget *entryadresse;
  GtkWidget *entrylog;
  GtkWidget *entrymdp;
  GtkWidget *entrycin1;
  GtkWidget *label23;
  GtkWidget *label22;
  GtkWidget *label16;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *combo3;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *radiobutton3;
  GtkWidget *label21;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *labelcin;
  GtkWidget *label18;
  GtkWidget *label17;
  GtkWidget *buttonprecedentmodifier;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label61;
  GtkWidget *buttonsuivantmodifier;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label62;
  GtkWidget *buttonannulermodif;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label29;
  GtkWidget *buttonmodifier;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label28;
  GtkWidget *buttonverifier;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image33;
  GtkWidget *label77;
  GtkWidget *combo4;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("modifier"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (modifier), fixed2);

  entryn = gtk_entry_new ();
  gtk_widget_show (entryn);
  gtk_fixed_put (GTK_FIXED (fixed2), entryn, 208, 120);
  gtk_widget_set_size_request (entryn, 176, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryn), 8226);

  entryp = gtk_entry_new ();
  gtk_widget_show (entryp);
  gtk_fixed_put (GTK_FIXED (fixed2), entryp, 216, 192);
  gtk_widget_set_size_request (entryp, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryp), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton4, 208, 352);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton5, 288, 352);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 2024, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton6, 376, 352);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  entryes = gtk_entry_new ();
  gtk_widget_show (entryes);
  gtk_fixed_put (GTK_FIXED (fixed2), entryes, 880, 104);
  gtk_widget_set_size_request (entryes, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryes), 8226);

  entrynt = gtk_entry_new ();
  gtk_widget_show (entrynt);
  gtk_fixed_put (GTK_FIXED (fixed2), entrynt, 880, 176);
  gtk_widget_set_size_request (entrynt, 184, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynt), 8226);

  entryadresse = gtk_entry_new ();
  gtk_widget_show (entryadresse);
  gtk_fixed_put (GTK_FIXED (fixed2), entryadresse, 888, 256);
  gtk_widget_set_size_request (entryadresse, 176, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresse), 8226);

  entrylog = gtk_entry_new ();
  gtk_widget_show (entrylog);
  gtk_fixed_put (GTK_FIXED (fixed2), entrylog, 896, 424);
  gtk_widget_set_size_request (entrylog, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrylog), 8226);

  entrymdp = gtk_entry_new ();
  gtk_widget_show (entrymdp);
  gtk_fixed_put (GTK_FIXED (fixed2), entrymdp, 896, 504);
  gtk_widget_set_size_request (entrymdp, 168, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymdp), 8226);

  entrycin1 = gtk_entry_new ();
  gtk_widget_show (entrycin1);
  gtk_fixed_put (GTK_FIXED (fixed2), entrycin1, 216, 264);
  gtk_widget_set_size_request (entrycin1, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycin1), 8226);

  label23 = gtk_label_new (_("Num\303\251ro de t\303\251lephone :"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed2), label23, 680, 168);
  gtk_widget_set_size_request (label23, 176, 56);

  label22 = gtk_label_new (_("Etat sanitaire :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 680, 80);
  gtk_widget_set_size_request (label22, 168, 81);

  label16 = gtk_label_new (_("MODIFIER UNE INFORMATION :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 416, 8);
  gtk_widget_set_size_request (label16, 312, 72);

  label24 = gtk_label_new (_("Adresse mail :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed2), label24, 680, 248);
  gtk_widget_set_size_request (label24, 160, 56);

  label25 = gtk_label_new (_("Poste actuel :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed2), label25, 672, 336);
  gtk_widget_set_size_request (label25, 176, 40);

  label26 = gtk_label_new (_("Login :"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed2), label26, 712, 416);
  gtk_widget_set_size_request (label26, 121, 57);

  label27 = gtk_label_new (_("Mot de passe :"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed2), label27, 696, 504);
  gtk_widget_set_size_request (label27, 152, 48);

  combo3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo3);
  gtk_fixed_put (GTK_FIXED (fixed2), combo3, 224, 504);
  gtk_widget_set_size_request (combo3, 189, 37);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo3), _("sdfgh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo3), _("hgfds"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo3), _("lkjhgfdx"));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton4, 288, 408);
  gtk_widget_set_size_request (radiobutton4, 156, 64);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton3, 152, 408);
  gtk_widget_set_size_request (radiobutton3, 156, 64);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  label21 = gtk_label_new (_("Etat civil :"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 56, 504);
  gtk_widget_set_size_request (label21, 136, 48);

  label20 = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed2), label20, 64, 400);
  gtk_widget_set_size_request (label20, 105, 73);

  label19 = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed2), label19, 32, 336);
  gtk_widget_set_size_request (label19, 160, 64);

  labelcin = gtk_label_new (_("Num\303\251ro CIN :"));
  gtk_widget_show (labelcin);
  gtk_fixed_put (GTK_FIXED (fixed2), labelcin, 48, 256);
  gtk_widget_set_size_request (labelcin, 160, 49);

  label18 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed2), label18, 48, 184);
  gtk_widget_set_size_request (label18, 152, 56);

  label17 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 96, 104);
  gtk_widget_set_size_request (label17, 105, 57);

  buttonprecedentmodifier = gtk_button_new ();
  gtk_widget_show (buttonprecedentmodifier);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonprecedentmodifier, 16, 912);
  gtk_widget_set_size_request (buttonprecedentmodifier, 152, 64);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (buttonprecedentmodifier), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("pr\303\251c\303\251dent"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox21), label61, FALSE, FALSE, 0);

  buttonsuivantmodifier = gtk_button_new ();
  gtk_widget_show (buttonsuivantmodifier);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonsuivantmodifier, 1016, 912);
  gtk_widget_set_size_request (buttonsuivantmodifier, 160, 64);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (buttonsuivantmodifier), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("suivant"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox22), label62, FALSE, FALSE, 0);

  buttonannulermodif = gtk_button_new ();
  gtk_widget_show (buttonannulermodif);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonannulermodif, 528, 848);
  gtk_widget_set_size_request (buttonannulermodif, 168, 64);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonannulermodif), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("annuler "));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox4), label29, FALSE, FALSE, 0);

  buttonmodifier = gtk_button_new ();
  gtk_widget_show (buttonmodifier);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonmodifier, 528, 768);
  gtk_widget_set_size_request (buttonmodifier, 168, 64);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonmodifier), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("modifier "));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox3), label28, FALSE, FALSE, 0);

  buttonverifier = gtk_button_new ();
  gtk_widget_show (buttonverifier);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonverifier, 528, 688);
  gtk_widget_set_size_request (buttonverifier, 168, 61);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (buttonverifier), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image33 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox33), image33, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("V\303\251rifier"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox33), label77, FALSE, FALSE, 0);

  combo4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo4);
  gtk_fixed_put (GTK_FIXED (fixed2), combo4, 888, 336);
  gtk_widget_set_size_request (combo4, 189, 37);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("kjhgf"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("lkjhgfd"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("lkjhgfds"));

  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedentmodifier, "clicked",
                    G_CALLBACK (on_buttonprecedentmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsuivantmodifier, "clicked",
                    G_CALLBACK (on_buttonsuivantmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonannulermodif, "clicked",
                    G_CALLBACK (on_buttonannulermodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifier, "clicked",
                    G_CALLBACK (on_buttonmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonverifier, "clicked",
                    G_CALLBACK (on_buttonverifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (modifier, entryn, "entryn");
  GLADE_HOOKUP_OBJECT (modifier, entryp, "entryp");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (modifier, entryes, "entryes");
  GLADE_HOOKUP_OBJECT (modifier, entrynt, "entrynt");
  GLADE_HOOKUP_OBJECT (modifier, entryadresse, "entryadresse");
  GLADE_HOOKUP_OBJECT (modifier, entrylog, "entrylog");
  GLADE_HOOKUP_OBJECT (modifier, entrymdp, "entrymdp");
  GLADE_HOOKUP_OBJECT (modifier, entrycin1, "entrycin1");
  GLADE_HOOKUP_OBJECT (modifier, label23, "label23");
  GLADE_HOOKUP_OBJECT (modifier, label22, "label22");
  GLADE_HOOKUP_OBJECT (modifier, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifier, label24, "label24");
  GLADE_HOOKUP_OBJECT (modifier, label25, "label25");
  GLADE_HOOKUP_OBJECT (modifier, label26, "label26");
  GLADE_HOOKUP_OBJECT (modifier, label27, "label27");
  GLADE_HOOKUP_OBJECT (modifier, combo3, "combo3");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (modifier, label21, "label21");
  GLADE_HOOKUP_OBJECT (modifier, label20, "label20");
  GLADE_HOOKUP_OBJECT (modifier, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifier, labelcin, "labelcin");
  GLADE_HOOKUP_OBJECT (modifier, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifier, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifier, buttonprecedentmodifier, "buttonprecedentmodifier");
  GLADE_HOOKUP_OBJECT (modifier, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (modifier, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (modifier, image21, "image21");
  GLADE_HOOKUP_OBJECT (modifier, label61, "label61");
  GLADE_HOOKUP_OBJECT (modifier, buttonsuivantmodifier, "buttonsuivantmodifier");
  GLADE_HOOKUP_OBJECT (modifier, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (modifier, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (modifier, image22, "image22");
  GLADE_HOOKUP_OBJECT (modifier, label62, "label62");
  GLADE_HOOKUP_OBJECT (modifier, buttonannulermodif, "buttonannulermodif");
  GLADE_HOOKUP_OBJECT (modifier, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (modifier, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (modifier, image4, "image4");
  GLADE_HOOKUP_OBJECT (modifier, label29, "label29");
  GLADE_HOOKUP_OBJECT (modifier, buttonmodifier, "buttonmodifier");
  GLADE_HOOKUP_OBJECT (modifier, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (modifier, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (modifier, image3, "image3");
  GLADE_HOOKUP_OBJECT (modifier, label28, "label28");
  GLADE_HOOKUP_OBJECT (modifier, buttonverifier, "buttonverifier");
  GLADE_HOOKUP_OBJECT (modifier, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (modifier, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (modifier, image33, "image33");
  GLADE_HOOKUP_OBJECT (modifier, label77, "label77");
  GLADE_HOOKUP_OBJECT (modifier, combo4, "combo4");

  return modifier;
}

GtkWidget*
create_supprimer (void)
{
  GtkWidget *supprimer;
  GtkWidget *fixed3;
  GtkWidget *cinsupp;
  GtkWidget *Num__ro_CIN;
  GtkWidget *label30;
  GtkWidget *buttonannuler;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label38;
  GtkWidget *buttsupprimer;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label63;
  GtkWidget *buttonprecedentsupprimer;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label64;
  GtkWidget *suivantsupprimer;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image29;
  GtkWidget *label73;

  supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer), _("supprimer"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (supprimer), fixed3);

  cinsupp = gtk_entry_new ();
  gtk_widget_show (cinsupp);
  gtk_fixed_put (GTK_FIXED (fixed3), cinsupp, 376, 208);
  gtk_widget_set_size_request (cinsupp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinsupp), 8226);

  Num__ro_CIN = gtk_label_new (_("Num\303\251ro CIN :"));
  gtk_widget_show (Num__ro_CIN);
  gtk_fixed_put (GTK_FIXED (fixed3), Num__ro_CIN, 232, 200);
  gtk_widget_set_size_request (Num__ro_CIN, 136, 40);

  label30 = gtk_label_new (_("SUPPRIMER UN AGENT :"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed3), label30, 336, 16);
  gtk_widget_set_size_request (label30, 216, 63);

  buttonannuler = gtk_button_new ();
  gtk_widget_show (buttonannuler);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonannuler, 456, 384);
  gtk_widget_set_size_request (buttonannuler, 160, 53);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonannuler), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("annuler "));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox6), label38, FALSE, FALSE, 0);

  buttsupprimer = gtk_button_new ();
  gtk_widget_show (buttsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), buttsupprimer, 280, 384);
  gtk_widget_set_size_request (buttsupprimer, 144, 48);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (buttsupprimer), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("supprimer\n"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox23), label63, FALSE, FALSE, 0);

  buttonprecedentsupprimer = gtk_button_new ();
  gtk_widget_show (buttonprecedentsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonprecedentsupprimer, 104, 384);
  gtk_widget_set_size_request (buttonprecedentsupprimer, 152, 48);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (buttonprecedentsupprimer), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("pr\303\251c\303\251dent"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox24), label64, FALSE, FALSE, 0);

  suivantsupprimer = gtk_button_new ();
  gtk_widget_show (suivantsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), suivantsupprimer, 648, 384);
  gtk_widget_set_size_request (suivantsupprimer, 152, 53);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (suivantsupprimer), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image29 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox29), image29, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("suivant"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox29), label73, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonannuler, "clicked",
                    G_CALLBACK (on_buttonannuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttsupprimer, "clicked",
                    G_CALLBACK (on_buttsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedentsupprimer, "clicked",
                    G_CALLBACK (on_buttonprecedentsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) suivantsupprimer, "clicked",
                    G_CALLBACK (on_suivantsupprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (supprimer, cinsupp, "cinsupp");
  GLADE_HOOKUP_OBJECT (supprimer, Num__ro_CIN, "Num__ro_CIN");
  GLADE_HOOKUP_OBJECT (supprimer, label30, "label30");
  GLADE_HOOKUP_OBJECT (supprimer, buttonannuler, "buttonannuler");
  GLADE_HOOKUP_OBJECT (supprimer, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (supprimer, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (supprimer, image6, "image6");
  GLADE_HOOKUP_OBJECT (supprimer, label38, "label38");
  GLADE_HOOKUP_OBJECT (supprimer, buttsupprimer, "buttsupprimer");
  GLADE_HOOKUP_OBJECT (supprimer, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (supprimer, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (supprimer, image23, "image23");
  GLADE_HOOKUP_OBJECT (supprimer, label63, "label63");
  GLADE_HOOKUP_OBJECT (supprimer, buttonprecedentsupprimer, "buttonprecedentsupprimer");
  GLADE_HOOKUP_OBJECT (supprimer, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (supprimer, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (supprimer, image24, "image24");
  GLADE_HOOKUP_OBJECT (supprimer, label64, "label64");
  GLADE_HOOKUP_OBJECT (supprimer, suivantsupprimer, "suivantsupprimer");
  GLADE_HOOKUP_OBJECT (supprimer, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (supprimer, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (supprimer, image29, "image29");
  GLADE_HOOKUP_OBJECT (supprimer, label73, "label73");

  return supprimer;
}

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed4;
  GtkWidget *label37;
  GtkWidget *dialog_action_area2;
  GtkWidget *annulerdialog2;
  GtkWidget *validerdialog2;

  dialog2 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog2), _("dialog2"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog2), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog2), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog2)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed4, TRUE, TRUE, 0);

  label37 = gtk_label_new (_("Vous etes sur(e) de retirer cet(te) agent(e) ?"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 208, 56);
  gtk_widget_set_size_request (label37, 1128, 512);

  dialog_action_area2 = GTK_DIALOG (dialog2)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  annulerdialog2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (annulerdialog2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), annulerdialog2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (annulerdialog2, GTK_CAN_DEFAULT);

  validerdialog2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (validerdialog2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), validerdialog2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (validerdialog2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) annulerdialog2, "clicked",
                    G_CALLBACK (on_annulerdialog2_clicked),
                    NULL);
  g_signal_connect ((gpointer) validerdialog2, "clicked",
                    G_CALLBACK (on_validerdialog2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog2, "dialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog2, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (dialog2, label37, "label37");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog2, annulerdialog2, "annulerdialog2");
  GLADE_HOOKUP_OBJECT (dialog2, validerdialog2, "validerdialog2");

  return dialog2;
}

GtkWidget*
create_afficher (void)
{
  GtkWidget *afficher;
  GtkWidget *fixed5;
  GtkWidget *treeview1;
  GtkWidget *buttonprecedentafficheragent;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label40;
  GtkWidget *buttonsuivantafficheragent;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label42;
  GtkWidget *buttonafficher;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label49;
  GtkWidget *label39;

  afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (afficher), _("afficher"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (afficher), fixed5);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 48, 176);
  gtk_widget_set_size_request (treeview1, 1304, 416);

  buttonprecedentafficheragent = gtk_button_new ();
  gtk_widget_show (buttonprecedentafficheragent);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonprecedentafficheragent, 16, 640);
  gtk_widget_set_size_request (buttonprecedentafficheragent, 152, 56);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonprecedentafficheragent), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("pr\303\251c\303\251dent "));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox7), label40, FALSE, FALSE, 0);

  buttonsuivantafficheragent = gtk_button_new ();
  gtk_widget_show (buttonsuivantafficheragent);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonsuivantafficheragent, 1328, 632);
  gtk_widget_set_size_request (buttonsuivantafficheragent, 152, 56);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonsuivantafficheragent), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("suivant "));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox9), label42, FALSE, FALSE, 0);

  buttonafficher = gtk_button_new ();
  gtk_widget_show (buttonafficher);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonafficher, 656, 640);
  gtk_widget_set_size_request (buttonafficher, 176, 53);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonafficher), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("afficher "));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox12), label49, FALSE, FALSE, 0);

  label39 = gtk_label_new (_("AFFICHER LE TABLEAU CONTENANT LES AGENTS :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed5), label39, 376, 24);
  gtk_widget_set_size_request (label39, 504, 136);

  g_signal_connect ((gpointer) buttonprecedentafficheragent, "clicked",
                    G_CALLBACK (on_buttonprecedentafficheragent_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsuivantafficheragent, "clicked",
                    G_CALLBACK (on_buttonsuivantafficheragent_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonafficher, "clicked",
                    G_CALLBACK (on_buttonafficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficher, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (afficher, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (afficher, buttonprecedentafficheragent, "buttonprecedentafficheragent");
  GLADE_HOOKUP_OBJECT (afficher, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (afficher, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (afficher, image7, "image7");
  GLADE_HOOKUP_OBJECT (afficher, label40, "label40");
  GLADE_HOOKUP_OBJECT (afficher, buttonsuivantafficheragent, "buttonsuivantafficheragent");
  GLADE_HOOKUP_OBJECT (afficher, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (afficher, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (afficher, image9, "image9");
  GLADE_HOOKUP_OBJECT (afficher, label42, "label42");
  GLADE_HOOKUP_OBJECT (afficher, buttonafficher, "buttonafficher");
  GLADE_HOOKUP_OBJECT (afficher, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (afficher, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (afficher, image12, "image12");
  GLADE_HOOKUP_OBJECT (afficher, label49, "label49");
  GLADE_HOOKUP_OBJECT (afficher, label39, "label39");

  return afficher;
}

GtkWidget*
create_tachesupplementaire (void)
{
  GtkWidget *tachesupplementaire;
  GtkWidget *fixed6;
  GtkWidget *treeview2;
  GtkWidget *precedentafficher;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label66;
  GtkWidget *suivantafficher;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label67;
  GtkWidget *label44;
  GtkWidget *label43;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label45;
  GtkWidget *butaffichres;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label46;

  tachesupplementaire = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (tachesupplementaire), _("tachesupplementaire"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (tachesupplementaire), fixed6);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview2, 224, 288);
  gtk_widget_set_size_request (treeview2, 680, 440);

  precedentafficher = gtk_button_new ();
  gtk_widget_show (precedentafficher);
  gtk_fixed_put (GTK_FIXED (fixed6), precedentafficher, 24, 784);
  gtk_widget_set_size_request (precedentafficher, 168, 61);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (precedentafficher), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label66 = gtk_label_new_with_mnemonic (_("pr\303\251c\303\251dent"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox26), label66, FALSE, FALSE, 0);

  suivantafficher = gtk_button_new ();
  gtk_widget_show (suivantafficher);
  gtk_fixed_put (GTK_FIXED (fixed6), suivantafficher, 880, 784);
  gtk_widget_set_size_request (suivantafficher, 168, 61);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (suivantafficher), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("suivant"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox27), label67, FALSE, FALSE, 0);

  label44 = gtk_label_new (_("selctionner la date de la r\303\251s\303\251rvation : "));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed6), label44, 240, 144);
  gtk_widget_set_size_request (label44, 312, 56);

  label43 = gtk_label_new (_("Liste de r\303\251servation faite par les citoyens \303\240 une date donn\303\251e :"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed6), label43, 272, 208);
  gtk_widget_set_size_request (label43, 464, 56);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton1, 536, 160);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton2, 624, 160);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton3, 720, 160);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label45 = gtk_label_new (_("AFFICHER LA LISTE DES R\303\211SERVATIONS FAITES PAR LES CITOYENS :"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed6), label45, 272, 48);
  gtk_widget_set_size_request (label45, 640, 81);

  butaffichres = gtk_button_new ();
  gtk_widget_show (butaffichres);
  gtk_fixed_put (GTK_FIXED (fixed6), butaffichres, 456, 784);
  gtk_widget_set_size_request (butaffichres, 176, 61);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (butaffichres), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("afficher "));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox10), label46, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) precedentafficher, "clicked",
                    G_CALLBACK (on_precedentafficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) suivantafficher, "clicked",
                    G_CALLBACK (on_suivantafficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) butaffichres, "clicked",
                    G_CALLBACK (on_butaffichres_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (tachesupplementaire, tachesupplementaire, "tachesupplementaire");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, precedentafficher, "precedentafficher");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, image26, "image26");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, label66, "label66");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, suivantafficher, "suivantafficher");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, image27, "image27");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, label67, "label67");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, label44, "label44");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, label43, "label43");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, label45, "label45");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, butaffichres, "butaffichres");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, image10, "image10");
  GLADE_HOOKUP_OBJECT (tachesupplementaire, label46, "label46");

  return tachesupplementaire;
}

GtkWidget*
create_menu (void)
{
  GtkWidget *menu;
  GtkWidget *fixed7;
  GtkWidget *label50;
  GtkWidget *butaffich;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label54;
  GtkWidget *butmodif;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label52;
  GtkWidget *butajout;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label51;
  GtkWidget *butsupprim;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label53;
  GtkWidget *butrech;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image32;
  GtkWidget *label76;
  GtkWidget *buttonaffichres;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label55;

  menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (menu), _("menu"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (menu), fixed7);

  label50 = gtk_label_new (_("ENTREZ VOTRE CHOIX CONCERNANT LES AGENTS :"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed7), label50, 152, 40);
  gtk_widget_set_size_request (label50, 856, 73);

  butaffich = gtk_button_new ();
  gtk_widget_show (butaffich);
  gtk_fixed_put (GTK_FIXED (fixed7), butaffich, 624, 376);
  gtk_widget_set_size_request (butaffich, 232, 104);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (butaffich), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox16), label54, FALSE, FALSE, 0);

  butmodif = gtk_button_new ();
  gtk_widget_show (butmodif);
  gtk_fixed_put (GTK_FIXED (fixed7), butmodif, 616, 176);
  gtk_widget_set_size_request (butmodif, 248, 101);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (butmodif), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox14), label52, FALSE, FALSE, 0);

  butajout = gtk_button_new ();
  gtk_widget_show (butajout);
  gtk_fixed_put (GTK_FIXED (fixed7), butajout, 336, 176);
  gtk_widget_set_size_request (butajout, 240, 101);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (butajout), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox13), label51, FALSE, FALSE, 0);

  butsupprim = gtk_button_new ();
  gtk_widget_show (butsupprim);
  gtk_fixed_put (GTK_FIXED (fixed7), butsupprim, 344, 376);
  gtk_widget_set_size_request (butsupprim, 232, 96);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (butsupprim), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox15), label53, FALSE, FALSE, 0);

  butrech = gtk_button_new ();
  gtk_widget_show (butrech);
  gtk_fixed_put (GTK_FIXED (fixed7), butrech, 632, 552);
  gtk_widget_set_size_request (butrech, 224, 93);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (butrech), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image32 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox32), image32, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox32), label76, FALSE, FALSE, 0);

  buttonaffichres = gtk_button_new ();
  gtk_widget_show (buttonaffichres);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonaffichres, 344, 560);
  gtk_widget_set_size_request (buttonaffichres, 232, 88);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonaffichres), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Afficher liste des reservations"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox17), label55, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) butaffich, "clicked",
                    G_CALLBACK (on_butaffich_clicked),
                    NULL);
  g_signal_connect ((gpointer) butmodif, "clicked",
                    G_CALLBACK (on_butmodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) butajout, "clicked",
                    G_CALLBACK (on_butajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) butsupprim, "clicked",
                    G_CALLBACK (on_butsupprim_clicked),
                    NULL);
  g_signal_connect ((gpointer) butrech, "clicked",
                    G_CALLBACK (on_butrech_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonaffichres, "clicked",
                    G_CALLBACK (on_buttonaffichres_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menu, menu, "menu");
  GLADE_HOOKUP_OBJECT (menu, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (menu, label50, "label50");
  GLADE_HOOKUP_OBJECT (menu, butaffich, "butaffich");
  GLADE_HOOKUP_OBJECT (menu, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (menu, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (menu, image16, "image16");
  GLADE_HOOKUP_OBJECT (menu, label54, "label54");
  GLADE_HOOKUP_OBJECT (menu, butmodif, "butmodif");
  GLADE_HOOKUP_OBJECT (menu, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (menu, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (menu, image14, "image14");
  GLADE_HOOKUP_OBJECT (menu, label52, "label52");
  GLADE_HOOKUP_OBJECT (menu, butajout, "butajout");
  GLADE_HOOKUP_OBJECT (menu, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (menu, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (menu, image13, "image13");
  GLADE_HOOKUP_OBJECT (menu, label51, "label51");
  GLADE_HOOKUP_OBJECT (menu, butsupprim, "butsupprim");
  GLADE_HOOKUP_OBJECT (menu, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (menu, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (menu, image15, "image15");
  GLADE_HOOKUP_OBJECT (menu, label53, "label53");
  GLADE_HOOKUP_OBJECT (menu, butrech, "butrech");
  GLADE_HOOKUP_OBJECT (menu, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (menu, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (menu, image32, "image32");
  GLADE_HOOKUP_OBJECT (menu, label76, "label76");
  GLADE_HOOKUP_OBJECT (menu, buttonaffichres, "buttonaffichres");
  GLADE_HOOKUP_OBJECT (menu, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (menu, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (menu, image17, "image17");
  GLADE_HOOKUP_OBJECT (menu, label55, "label55");

  return menu;
}

GtkWidget*
create_chercher (void)
{
  GtkWidget *chercher;
  GtkWidget *fixed8;
  GtkWidget *entryrecherchercin;
  GtkWidget *label57;
  GtkWidget *resultat;
  GtkWidget *buttonchercher;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label58;
  GtkWidget *label56;
  GtkWidget *buttonprecedentchercher;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label74;
  GtkWidget *bouttonsuivantchercher;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image31;
  GtkWidget *label75;

  chercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (chercher), _("chercher "));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (chercher), fixed8);

  entryrecherchercin = gtk_entry_new ();
  gtk_widget_show (entryrecherchercin);
  gtk_fixed_put (GTK_FIXED (fixed8), entryrecherchercin, 280, 208);
  gtk_widget_set_size_request (entryrecherchercin, 272, 51);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryrecherchercin), 8226);

  label57 = gtk_label_new (_("Entrez le num\303\251ro CIN de l'agent :"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed8), label57, 24, 200);
  gtk_widget_set_size_request (label57, 272, 73);

  resultat = gtk_label_new ("");
  gtk_widget_show (resultat);
  gtk_fixed_put (GTK_FIXED (fixed8), resultat, 176, 456);
  gtk_widget_set_size_request (resultat, 256, 41);

  buttonchercher = gtk_button_new ();
  gtk_widget_show (buttonchercher);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonchercher, 192, 368);
  gtk_widget_set_size_request (buttonchercher, 248, 53);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonchercher), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox18), label58, FALSE, FALSE, 0);

  label56 = gtk_label_new (_("RECHERCHE D'UN AGENT :"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed8), label56, 208, 32);
  gtk_widget_set_size_request (label56, 360, 81);

  buttonprecedentchercher = gtk_button_new ();
  gtk_widget_show (buttonprecedentchercher);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonprecedentchercher, 160, 600);
  gtk_widget_set_size_request (buttonprecedentchercher, 168, 61);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (buttonprecedentchercher), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("pr\303\251c\303\251dent"));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox30), label74, FALSE, FALSE, 0);

  bouttonsuivantchercher = gtk_button_new ();
  gtk_widget_show (bouttonsuivantchercher);
  gtk_fixed_put (GTK_FIXED (fixed8), bouttonsuivantchercher, 360, 600);
  gtk_widget_set_size_request (bouttonsuivantchercher, 160, 61);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (bouttonsuivantchercher), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image31 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox31), image31, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("suivant"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox31), label75, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonchercher, "clicked",
                    G_CALLBACK (on_buttonchercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonprecedentchercher, "clicked",
                    G_CALLBACK (on_buttonprecedentchercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) bouttonsuivantchercher, "clicked",
                    G_CALLBACK (on_bouttonsuivantchercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (chercher, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (chercher, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (chercher, entryrecherchercin, "entryrecherchercin");
  GLADE_HOOKUP_OBJECT (chercher, label57, "label57");
  GLADE_HOOKUP_OBJECT (chercher, resultat, "resultat");
  GLADE_HOOKUP_OBJECT (chercher, buttonchercher, "buttonchercher");
  GLADE_HOOKUP_OBJECT (chercher, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (chercher, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (chercher, image18, "image18");
  GLADE_HOOKUP_OBJECT (chercher, label58, "label58");
  GLADE_HOOKUP_OBJECT (chercher, label56, "label56");
  GLADE_HOOKUP_OBJECT (chercher, buttonprecedentchercher, "buttonprecedentchercher");
  GLADE_HOOKUP_OBJECT (chercher, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (chercher, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (chercher, image30, "image30");
  GLADE_HOOKUP_OBJECT (chercher, label74, "label74");
  GLADE_HOOKUP_OBJECT (chercher, bouttonsuivantchercher, "bouttonsuivantchercher");
  GLADE_HOOKUP_OBJECT (chercher, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (chercher, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (chercher, image31, "image31");
  GLADE_HOOKUP_OBJECT (chercher, label75, "label75");

  return chercher;
}

GtkWidget*
create_goodbye (void)
{
  GtkWidget *goodbye;
  GtkWidget *fixed9;
  GtkWidget *label70;
  GtkWidget *label71;
  GtkWidget *label79;
  GtkWidget *label78;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton4;
  GtkWidget *label72;
  GtkWidget *buttonquitter;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label69;

  goodbye = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (goodbye), _("goodbye"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (goodbye), fixed9);

  label70 = gtk_label_new (_("Merci \303\240 nos employ\303\251s !"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed9), label70, 360, 0);
  gtk_widget_set_size_request (label70, 352, 160);

  label71 = gtk_label_new (_("       Votre engagement et votre travail sont essentiels \303\240 notre r\303\251ussite. Nous sommes reconnaissants                                                  \n        pour tout ce que vous faites chaque jour pour am\303\251liorer notre service .\n\n\n                                                                               "));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed9), label71, 232, 128);
  gtk_widget_set_size_request (label71, 688, 240);

  label79 = gtk_label_new (_("S\303\251lectionnez votre avis :"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed9), label79, 104, 608);
  gtk_widget_set_size_request (label79, 232, 73);

  label78 = gtk_label_new (_("L'avis de nos administrateurs / administratrices de notre service est important pour nous !"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed9), label78, 232, 440);
  gtk_widget_set_size_request (label78, 664, 121);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Pas mal"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton3, 784, 632);
  gtk_widget_set_size_request (checkbutton3, 118, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Moyen"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton2, 600, 632);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Excellent"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton1, 416, 632);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("Mauvais"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton4, 920, 632);
  gtk_widget_set_size_request (checkbutton4, 118, 24);

  label72 = gtk_label_new (_("Bravo et merci !\n                                                                               \nL'equipe de Parky ."));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed9), label72, 328, 296);
  gtk_widget_set_size_request (label72, 528, 137);

  buttonquitter = gtk_button_new ();
  gtk_widget_show (buttonquitter);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonquitter, 888, 808);
  gtk_widget_set_size_request (buttonquitter, 192, 61);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (buttonquitter), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox28), label69, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonquitter, "clicked",
                    G_CALLBACK (on_buttonquitter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (goodbye, goodbye, "goodbye");
  GLADE_HOOKUP_OBJECT (goodbye, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (goodbye, label70, "label70");
  GLADE_HOOKUP_OBJECT (goodbye, label71, "label71");
  GLADE_HOOKUP_OBJECT (goodbye, label79, "label79");
  GLADE_HOOKUP_OBJECT (goodbye, label78, "label78");
  GLADE_HOOKUP_OBJECT (goodbye, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (goodbye, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (goodbye, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (goodbye, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (goodbye, label72, "label72");
  GLADE_HOOKUP_OBJECT (goodbye, buttonquitter, "buttonquitter");
  GLADE_HOOKUP_OBJECT (goodbye, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (goodbye, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (goodbye, image28, "image28");
  GLADE_HOOKUP_OBJECT (goodbye, label69, "label69");

  return goodbye;
}

