/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  /*GtkWidget *ajouter;
  GtkWidget *modifier;
  GtkWidget *supprimer;
  GtkWidget *dialog2;
  GtkWidget *afficher;
  GtkWidget *tachesupplementaire;*/
  GtkWidget *menu;
  /*GtkWidget *chercher;*/
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*ajouter = create_ajouter ();
  gtk_widget_show (ajouter);
  modifier = create_modifier ();
  gtk_widget_show (modifier);
  supprimer = create_supprimer ();
  gtk_widget_show (supprimer);
  dialog2 = create_dialog2 ();
  gtk_widget_show (dialog2);
  afficher = create_afficher ();
  gtk_widget_show (afficher);
  tachesupplementaire= create_tachesupplementaire ();
  gtk_widget_show (tachesupplementaire);*/
  menu= create_menu ();
  gtk_widget_show (menu);
  /*chercher = create_chercher ();
  gtk_widget_show (chercher);*/
  gtk_main ();
  return 0;
}

