/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *type_de_demande;
  GtkWidget *note_de_satisfaction;
  GtkWidget *date_de_reclamation;
  GtkWidget *cat__gorie;
  GtkObject *spinbuttonjour_adj;
  GtkWidget *spinbuttonjour;
  GtkObject *spinbuttonmois_adj;
  GtkWidget *spinbuttonmois;
  GtkObject *spinbuttonannes_adj;
  GtkWidget *spinbuttonannes;
  GtkWidget *entry2;
  GtkWidget *entry_categorie;
  GtkWidget *RadioButton1;
  GSList *RadioButton1_group = NULL;
  GtkWidget *reclamation;
  GtkWidget *AJOUTSUCC;
  GtkWidget *contenu;
  GtkWidget *entry6;
  GtkWidget *id_client;
  GtkWidget *label42;
  GtkWidget *button_suivant1;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label34;
  GtkWidget *CheckButton1;
  GtkWidget *Ajouter;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label16;
  GtkWidget *label49;
  GtkWidget *ajouter_un_avis;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *button_precedent;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label31;
  GtkWidget *button_modifier;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label32;
  GtkWidget *MODIFSUCC;
  GtkWidget *button_suivant;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label33;
  GtkWidget *fixed3;
  GtkWidget *entry3;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkWidget *entry4;
  GtkWidget *label28;
  GtkWidget *label22;
  GtkWidget *label25;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *button_cherche;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label35;
  GtkWidget *combobox1;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *checkbutton1;
  GtkWidget *label29;
  GtkWidget *entry7;
  GtkWidget *label45;
  GtkWidget *button_afficher;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label21;
  GtkWidget *modifier_un_avis;
  GtkWidget *fixed4;
  GtkWidget *entry5;
  GtkWidget *button_precedent2;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label39;
  GtkWidget *button_suivant3;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label40;
  GtkWidget *label37;
  GtkWidget *button_supprimer;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label38;
  GtkWidget *label50;
  GtkWidget *supprimr_un_avis_;
  GtkWidget *fixed6;
  GtkWidget *treeview2;
  GtkWidget *button_affichagetous;
  GtkWidget *button_precedent555;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label46;
  GtkWidget *button_suivant555;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label47;
  GtkWidget *label43;
  GtkWidget *afficher;
  GtkWidget *fixed7;
  GtkWidget *treeview3;
  GtkWidget *button_trier;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label44;
  GtkWidget *button_precedent666;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label48;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *label36;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  notebook = gtk_notebook_new ();
  gtk_widget_show (notebook);
  gtk_container_add (GTK_CONTAINER (window1), notebook);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 80, 8);
  gtk_widget_set_size_request (entry1, 72, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1, 168, 232);
  gtk_widget_set_size_request (spinbutton1, 40, 27);

  type_de_demande = gtk_label_new (_("type de demande:"));
  gtk_widget_show (type_de_demande);
  gtk_fixed_put (GTK_FIXED (fixed1), type_de_demande, 16, 128);
  gtk_widget_set_size_request (type_de_demande, 120, 24);

  note_de_satisfaction = gtk_label_new (_("note de satisfaction:"));
  gtk_widget_show (note_de_satisfaction);
  gtk_fixed_put (GTK_FIXED (fixed1), note_de_satisfaction, 16, 240);
  gtk_widget_set_size_request (note_de_satisfaction, 136, 16);

  date_de_reclamation = gtk_label_new (_("date de reclamation:"));
  gtk_widget_show (date_de_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed1), date_de_reclamation, 16, 296);
  gtk_widget_set_size_request (date_de_reclamation, 144, 16);

  cat__gorie = gtk_label_new (_("cat\303\251gorie:"));
  gtk_widget_show (cat__gorie);
  gtk_fixed_put (GTK_FIXED (fixed1), cat__gorie, 0, 184);
  gtk_widget_set_size_request (cat__gorie, 104, 24);

  spinbuttonjour_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonjour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjour_adj), 1, 0);
  gtk_widget_show (spinbuttonjour);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonjour, 168, 288);
  gtk_widget_set_size_request (spinbuttonjour, 48, 27);

  spinbuttonmois_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonmois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmois_adj), 1, 0);
  gtk_widget_show (spinbuttonmois);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonmois, 240, 288);
  gtk_widget_set_size_request (spinbuttonmois, 48, 27);

  spinbuttonannes_adj = gtk_adjustment_new (0, 0, 3000, 1, 10, 10);
  spinbuttonannes = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonannes_adj), 1, 0);
  gtk_widget_show (spinbuttonannes);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonannes, 312, 288);
  gtk_widget_set_size_request (spinbuttonannes, 72, 27);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 96, 64);
  gtk_widget_set_size_request (entry2, 232, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry_categorie = gtk_combo_box_new_text ();
  gtk_widget_show (entry_categorie);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_categorie, 168, 184);
  gtk_widget_set_size_request (entry_categorie, 208, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_categorie), _("cat1 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_categorie), _("cat2 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry_categorie), _("cat3"));

  RadioButton1 = gtk_radio_button_new_with_mnemonic (NULL, _("avis"));
  gtk_widget_show (RadioButton1);
  gtk_fixed_put (GTK_FIXED (fixed1), RadioButton1, 168, 128);
  gtk_widget_set_size_request (RadioButton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RadioButton1), RadioButton1_group);
  RadioButton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RadioButton1));

  reclamation = gtk_radio_button_new_with_mnemonic (NULL, _("reclamation"));
  gtk_widget_show (reclamation);
  gtk_fixed_put (GTK_FIXED (fixed1), reclamation, 264, 128);
  gtk_widget_set_size_request (reclamation, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (reclamation), RadioButton1_group);
  RadioButton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (reclamation));

  AJOUTSUCC = gtk_label_new ("");
  gtk_widget_show (AJOUTSUCC);
  gtk_fixed_put (GTK_FIXED (fixed1), AJOUTSUCC, 520, 200);
  gtk_widget_set_size_request (AJOUTSUCC, 49, 17);

  contenu = gtk_label_new (_("contenu:"));
  gtk_widget_show (contenu);
  gtk_fixed_put (GTK_FIXED (fixed1), contenu, 0, 88);
  gtk_widget_set_size_request (contenu, 88, 16);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed1), entry6, 96, 32);
  gtk_widget_set_size_request (entry6, 80, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  id_client = gtk_label_new (_("id_client:"));
  gtk_widget_show (id_client);
  gtk_fixed_put (GTK_FIXED (fixed1), id_client, 16, 16);
  gtk_widget_set_size_request (id_client, 64, 16);

  label42 = gtk_label_new (_("id-parking:"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed1), label42, 8, 40);
  gtk_widget_set_size_request (label42, 88, 17);

  button_suivant1 = gtk_button_new ();
  gtk_widget_show (button_suivant1);
  gtk_fixed_put (GTK_FIXED (fixed1), button_suivant1, 1008, 496);
  gtk_widget_set_size_request (button_suivant1, 136, 53);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_suivant1), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("suivant"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox9), label34, FALSE, FALSE, 0);

  CheckButton1 = gtk_check_button_new_with_mnemonic (_("urgent"));
  gtk_widget_show (CheckButton1);
  gtk_fixed_put (GTK_FIXED (fixed1), CheckButton1, 16, 352);
  gtk_widget_set_size_request (CheckButton1, 120, 24);

  Ajouter = gtk_button_new ();
  gtk_widget_show (Ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), Ajouter, 184, 424);
  gtk_widget_set_size_request (Ajouter, 128, 64);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (Ajouter), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox2), label16, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label49 = gtk_label_new (_("<u><span font_size=\"20000\" > <span foreground=\"red\">--Ajouter Avis--</span></span></u>\n"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed1), label49, 416, 24);
  gtk_widget_set_size_request (label49, 280, 48);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  ajouter_un_avis = gtk_label_new (_("<span foreground=\"navy\" weight=\"bold\">Ajouter un avis</span>\n"));
  gtk_widget_show (ajouter_un_avis);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), ajouter_un_avis);
  gtk_label_set_use_markup (GTK_LABEL (ajouter_un_avis), TRUE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 0, 0);
  gtk_widget_set_size_request (treeview1, 736, 192);

  button_precedent = gtk_button_new ();
  gtk_widget_show (button_precedent);
  gtk_fixed_put (GTK_FIXED (fixed2), button_precedent, 16, 504);
  gtk_widget_set_size_request (button_precedent, 138, 53);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_precedent), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("precedent"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox6), label31, FALSE, FALSE, 0);

  button_modifier = gtk_button_new ();
  gtk_widget_show (button_modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), button_modifier, 240, 504);
  gtk_widget_set_size_request (button_modifier, 114, 53);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_modifier), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox7), label32, FALSE, FALSE, 0);

  MODIFSUCC = gtk_label_new ("");
  gtk_widget_show (MODIFSUCC);
  gtk_fixed_put (GTK_FIXED (fixed2), MODIFSUCC, 568, 336);
  gtk_widget_set_size_request (MODIFSUCC, 49, 17);

  button_suivant = gtk_button_new ();
  gtk_widget_show (button_suivant);
  gtk_fixed_put (GTK_FIXED (fixed2), button_suivant, 448, 504);
  gtk_widget_set_size_request (button_suivant, 152, 56);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_suivant), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("suivant"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox8), label33, FALSE, FALSE, 0);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed3, 24, 192);
  gtk_widget_set_size_request (fixed3, 544, 336);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 288, 8);
  gtk_widget_set_size_request (entry3, 72, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 160, 192);
  gtk_widget_set_size_request (spinbutton2, 48, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton3, 160, 232);
  gtk_widget_set_size_request (spinbutton3, 48, 27);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton4, 216, 232);
  gtk_widget_set_size_request (spinbutton4, 48, 27);

  spinbutton5_adj = gtk_adjustment_new (0, 0, 3000, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton5, 272, 232);
  gtk_widget_set_size_request (spinbutton5, 72, 27);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 88, 40);
  gtk_widget_set_size_request (entry4, 232, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label28 = gtk_label_new (_("id_client:"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed3), label28, 224, 16);
  gtk_widget_set_size_request (label28, 64, 16);

  label22 = gtk_label_new (_("type de demande:"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 16, 112);
  gtk_widget_set_size_request (label22, 120, 24);

  label25 = gtk_label_new (_("cat\303\251gorie:"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 0, 144);
  gtk_widget_set_size_request (label25, 104, 24);

  label23 = gtk_label_new (_("note de satisfaction:"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 8, 192);
  gtk_widget_set_size_request (label23, 136, 16);

  label24 = gtk_label_new (_("date de reclamation:"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 8, 240);
  gtk_widget_set_size_request (label24, 144, 16);

  button_cherche = gtk_button_new ();
  gtk_widget_show (button_cherche);
  gtk_fixed_put (GTK_FIXED (fixed3), button_cherche, 392, 8);
  gtk_widget_set_size_request (button_cherche, 88, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_cherche), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("cherche"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox10), label35, FALSE, FALSE, 0);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1, 128, 144);
  gtk_widget_set_size_request (combobox1, 208, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("cat1 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("cat2 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("cat3"));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("avis"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton1, 152, 112);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("reclamation"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton2, 280, 112);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("urgent "));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1, 8, 272);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  label29 = gtk_label_new (_("contenu:"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed3), label29, 0, 64);
  gtk_widget_set_size_request (label29, 88, 16);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed3), entry7, 88, 8);
  gtk_widget_set_size_request (entry7, 80, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label45 = gtk_label_new (_("id-parking:"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed3), label45, 0, 16);
  gtk_widget_set_size_request (label45, 88, 17);

  button_afficher = gtk_button_new ();
  gtk_widget_show (button_afficher);
  gtk_fixed_put (GTK_FIXED (fixed2), button_afficher, 744, 104);
  gtk_widget_set_size_request (button_afficher, 88, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_afficher), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-undelete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox3), label21, FALSE, FALSE, 0);

  modifier_un_avis = gtk_label_new (_("<span foreground=\"navy\" weight=\"bold\">Modefier un avis</span>\n"));
  gtk_widget_show (modifier_un_avis);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), modifier_un_avis);
  gtk_label_set_use_markup (GTK_LABEL (modifier_un_avis), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook), fixed4);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 520, 128);
  gtk_widget_set_size_request (entry5, 88, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  button_precedent2 = gtk_button_new ();
  gtk_widget_show (button_precedent2);
  gtk_fixed_put (GTK_FIXED (fixed4), button_precedent2, 40, 480);
  gtk_widget_set_size_request (button_precedent2, 136, 64);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_precedent2), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("precedent "));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox12), label39, FALSE, FALSE, 0);

  button_suivant3 = gtk_button_new ();
  gtk_widget_show (button_suivant3);
  gtk_fixed_put (GTK_FIXED (fixed4), button_suivant3, 1032, 480);
  gtk_widget_set_size_request (button_suivant3, 130, 61);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_suivant3), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("suivant"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox13), label40, FALSE, FALSE, 0);

  label37 = gtk_label_new (_("id_client:"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 456, 136);
  gtk_widget_set_size_request (label37, 64, 16);

  button_supprimer = gtk_button_new ();
  gtk_widget_show (button_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), button_supprimer, 624, 104);
  gtk_widget_set_size_request (button_supprimer, 160, 72);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_supprimer), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("suprrimer"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox11), label38, FALSE, FALSE, 0);

  label50 = gtk_label_new (_("<u><span font_size=\"20000\" > <span foreground=\"red\">--Supprimer Avis--</span></span></u>"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed4), label50, 464, 16);
  gtk_widget_set_size_request (label50, 264, 48);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  supprimr_un_avis_ = gtk_label_new (_("<span foreground=\"navy\" weight=\"bold\">Supprimer un avis</span>\n"));
  gtk_widget_show (supprimr_un_avis_);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 2), supprimr_un_avis_);
  gtk_label_set_use_markup (GTK_LABEL (supprimr_un_avis_), TRUE);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook), fixed6);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview2, 224, 56);
  gtk_widget_set_size_request (treeview2, 824, 360);

  button_affichagetous = gtk_button_new_with_mnemonic (_("affichage "));
  gtk_widget_show (button_affichagetous);
  gtk_fixed_put (GTK_FIXED (fixed6), button_affichagetous, 112, 168);
  gtk_widget_set_size_request (button_affichagetous, 90, 29);

  button_precedent555 = gtk_button_new ();
  gtk_widget_show (button_precedent555);
  gtk_fixed_put (GTK_FIXED (fixed6), button_precedent555, 48, 496);
  gtk_widget_set_size_request (button_precedent555, 144, 53);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_precedent555), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("precedent"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox15), label46, FALSE, FALSE, 0);

  button_suivant555 = gtk_button_new ();
  gtk_widget_show (button_suivant555);
  gtk_fixed_put (GTK_FIXED (fixed6), button_suivant555, 1096, 496);
  gtk_widget_set_size_request (button_suivant555, 146, 53);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_suivant555), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("suivant"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox16), label47, FALSE, FALSE, 0);

  label43 = gtk_label_new (_("<u><span font_size=\"20000\" > <span foreground=\"red\">--affichage Avis--</span></span></u>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed6), label43, 408, 16);
  gtk_widget_set_size_request (label43, 376, 32);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  afficher = gtk_label_new (_("<span foreground=\"navy\" weight=\"bold\">Afficher un avis</span>\n "));
  gtk_widget_show (afficher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 3), afficher);
  gtk_label_set_use_markup (GTK_LABEL (afficher), TRUE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook), fixed7);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview3, 200, 112);
  gtk_widget_set_size_request (treeview3, 848, 392);

  button_trier = gtk_button_new ();
  gtk_widget_show (button_trier);
  gtk_fixed_put (GTK_FIXED (fixed7), button_trier, 104, 120);
  gtk_widget_set_size_request (button_trier, 88, 37);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_trier), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("trier"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox14), label44, FALSE, FALSE, 0);

  button_precedent666 = gtk_button_new ();
  gtk_widget_show (button_precedent666);
  gtk_fixed_put (GTK_FIXED (fixed7), button_precedent666, 16, 504);
  gtk_widget_set_size_request (button_precedent666, 136, 56);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_precedent666), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("precedent"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox17), label48, FALSE, FALSE, 0);

  label51 = gtk_label_new (_("<u><span font_size=\"20000\" > <span foreground=\"red\">--trier Parking --</span></span></u>"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed7), label51, 512, 24);
  gtk_widget_set_size_request (label51, 200, 41);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  label52 = gtk_label_new (_("<span color=\"green\"> PS:LES PARKINGS SONT TRIEE SELON LA NOTE DE SATISFACTION DES CLIENT</span>\n"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed7), label52, 96, 88);
  gtk_widget_set_size_request (label52, 480, 16);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  label36 = gtk_label_new (_("<span foreground=\"navy\" weight=\"bold\">Trier parking</span>\n"));
  gtk_widget_show (label36);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 4), label36);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label36), 0.5, 0.48);

  g_signal_connect ((gpointer) button_suivant1, "clicked",
                    G_CALLBACK (on_button_suivant1_clicked),
                    NULL);
  g_signal_connect ((gpointer) Ajouter, "clicked",
                    G_CALLBACK (on_Ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_precedent, "clicked",
                    G_CALLBACK (on_button_precedent_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier, "clicked",
                    G_CALLBACK (on_button_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_suivant, "clicked",
                    G_CALLBACK (on_button_suivant_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cherche, "clicked",
                    G_CALLBACK (on_button_cherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher, "clicked",
                    G_CALLBACK (on_button_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_precedent2, "clicked",
                    G_CALLBACK (on_button_precedent2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_suivant3, "clicked",
                    G_CALLBACK (on_button_suivant3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer, "clicked",
                    G_CALLBACK (on_button_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affichagetous, "clicked",
                    G_CALLBACK (on_button_affichagetous_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_precedent555, "clicked",
                    G_CALLBACK (on_button_precedent555_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_suivant555, "clicked",
                    G_CALLBACK (on_button_suivant555_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_trier, "clicked",
                    G_CALLBACK (on_button_trier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_precedent666, "clicked",
                    G_CALLBACK (on_button_precedent666_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook, "notebook");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window1, type_de_demande, "type_de_demande");
  GLADE_HOOKUP_OBJECT (window1, note_de_satisfaction, "note_de_satisfaction");
  GLADE_HOOKUP_OBJECT (window1, date_de_reclamation, "date_de_reclamation");
  GLADE_HOOKUP_OBJECT (window1, cat__gorie, "cat__gorie");
  GLADE_HOOKUP_OBJECT (window1, spinbuttonjour, "spinbuttonjour");
  GLADE_HOOKUP_OBJECT (window1, spinbuttonmois, "spinbuttonmois");
  GLADE_HOOKUP_OBJECT (window1, spinbuttonannes, "spinbuttonannes");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, entry_categorie, "entry_categorie");
  GLADE_HOOKUP_OBJECT (window1, RadioButton1, "RadioButton1");
  GLADE_HOOKUP_OBJECT (window1, reclamation, "reclamation");
  GLADE_HOOKUP_OBJECT (window1, AJOUTSUCC, "AJOUTSUCC");
  GLADE_HOOKUP_OBJECT (window1, contenu, "contenu");
  GLADE_HOOKUP_OBJECT (window1, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window1, id_client, "id_client");
  GLADE_HOOKUP_OBJECT (window1, label42, "label42");
  GLADE_HOOKUP_OBJECT (window1, button_suivant1, "button_suivant1");
  GLADE_HOOKUP_OBJECT (window1, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, CheckButton1, "CheckButton1");
  GLADE_HOOKUP_OBJECT (window1, Ajouter, "Ajouter");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, label49, "label49");
  GLADE_HOOKUP_OBJECT (window1, ajouter_un_avis, "ajouter_un_avis");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, button_precedent, "button_precedent");
  GLADE_HOOKUP_OBJECT (window1, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1, image6, "image6");
  GLADE_HOOKUP_OBJECT (window1, label31, "label31");
  GLADE_HOOKUP_OBJECT (window1, button_modifier, "button_modifier");
  GLADE_HOOKUP_OBJECT (window1, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window1, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window1, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, MODIFSUCC, "MODIFSUCC");
  GLADE_HOOKUP_OBJECT (window1, button_suivant, "button_suivant");
  GLADE_HOOKUP_OBJECT (window1, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window1, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window1, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (window1, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (window1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, button_cherche, "button_cherche");
  GLADE_HOOKUP_OBJECT (window1, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, label35, "label35");
  GLADE_HOOKUP_OBJECT (window1, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window1, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window1, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window1, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window1, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window1, label45, "label45");
  GLADE_HOOKUP_OBJECT (window1, button_afficher, "button_afficher");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");
  GLADE_HOOKUP_OBJECT (window1, modifier_un_avis, "modifier_un_avis");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window1, button_precedent2, "button_precedent2");
  GLADE_HOOKUP_OBJECT (window1, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image12, "image12");
  GLADE_HOOKUP_OBJECT (window1, label39, "label39");
  GLADE_HOOKUP_OBJECT (window1, button_suivant3, "button_suivant3");
  GLADE_HOOKUP_OBJECT (window1, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, label40, "label40");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, button_supprimer, "button_supprimer");
  GLADE_HOOKUP_OBJECT (window1, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window1, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window1, image11, "image11");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, label50, "label50");
  GLADE_HOOKUP_OBJECT (window1, supprimr_un_avis_, "supprimr_un_avis_");
  GLADE_HOOKUP_OBJECT (window1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window1, button_affichagetous, "button_affichagetous");
  GLADE_HOOKUP_OBJECT (window1, button_precedent555, "button_precedent555");
  GLADE_HOOKUP_OBJECT (window1, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window1, image15, "image15");
  GLADE_HOOKUP_OBJECT (window1, label46, "label46");
  GLADE_HOOKUP_OBJECT (window1, button_suivant555, "button_suivant555");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window1, image16, "image16");
  GLADE_HOOKUP_OBJECT (window1, label47, "label47");
  GLADE_HOOKUP_OBJECT (window1, label43, "label43");
  GLADE_HOOKUP_OBJECT (window1, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (window1, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window1, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window1, button_trier, "button_trier");
  GLADE_HOOKUP_OBJECT (window1, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, label44, "label44");
  GLADE_HOOKUP_OBJECT (window1, button_precedent666, "button_precedent666");
  GLADE_HOOKUP_OBJECT (window1, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window1, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window1, image17, "image17");
  GLADE_HOOKUP_OBJECT (window1, label48, "label48");
  GLADE_HOOKUP_OBJECT (window1, label51, "label51");
  GLADE_HOOKUP_OBJECT (window1, label52, "label52");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");

  return window1;
}

